import Head from 'next/head'

import { Boats, Layout } from 'components'

import { About } from './About'
import { Cards } from './Cards'
import { Intro } from './Intro'

export const HomePage = () => (
  <>
    <Head>
      <title>Next — Яхта-ялта</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Layout>
      <Intro />
      <Cards />
      <Boats />
    </Layout>
  </>
)

export default HomePage
